name: Publish avitools
# Controls when the action will run. 
on:
  release:
    types: [created]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      
      - name: Run build
        run: sh build.sh
        id: createbuild
      - name: Fix permissions 
        run: |
          chmod ugo+rwx /var/lib/docker/image/aufs/imagedb/content/sha256
        
      - name: Upload the artifact 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          
          upload_url: "${{ github.event.release.upload_url }}"
          asset_name: avitoolsimage
          asset_path: '/var/lib/docker/image/aufs/imagedb/content/sha256/avitoolsimage'
          asset_content_type: application/octet-stream 
      
          
      
      
